import { useState } from "react";
import { Link } from "react-router-dom";

const api = (url, options = {}) => fetch(url, { ...options, headers: { "Content-Type": "application/json", Authorization: `Bearer ${localStorage.getItem("tb-token") || ""}`, ...options.headers } });

export default function Planner() {
  const [notice, setNotice] = useState(""); const [saving, setSaving] = useState(false); const [service, setService] = useState("Hotel stay");
  const submit = async (event) => { event.preventDefault(); if (!localStorage.getItem("tb-token")) return setNotice("Please sign in as a user first."); setSaving(true); const form = new FormData(event.currentTarget); const data = { title: form.get("title"), dates: form.get("dates"), destinations: form.get("destinations").split(",") }; const response = await api("/api/itineraries", { method: "POST", body: JSON.stringify(data) }); const result = await response.json(); setSaving(false); setNotice(response.ok ? "Your itinerary has been saved." : result.message); if (response.ok) event.currentTarget.reset(); };
  const book = async (event) => { event.preventDefault(); if (!localStorage.getItem("tb-token")) return setNotice("Please sign in as a user first."); const form = new FormData(event.currentTarget); const response = await api("/api/booking-enquiries", { method: "POST", body: JSON.stringify({ ...Object.fromEntries(form), service }) }); const result = await response.json(); setNotice(response.ok ? "Booking enquiry received. A travel partner can contact you next." : result.message); if (response.ok) event.currentTarget.reset(); };
  return <main className="page planner-page"><div className="page-heading"><p className="intro-label">PLAN YOUR JOURNEY</p><h1>Build an India itinerary</h1><p>Save a personalised route and send a hotel or transport enquiry. Payments are handled by an approved travel partner after confirmation.</p></div><div className="planner-grid"><form className="planner-card" onSubmit={submit}><h2>My itinerary</h2><input name="title" required placeholder="Trip name, e.g. Golden Triangle" /><input name="dates" placeholder="Travel dates" /><textarea name="destinations" required placeholder="Destinations, separated by commas" /><button disabled={saving}>{saving ? "Saving…" : "Save itinerary"}</button></form><form className="planner-card" onSubmit={book}><h2>Hotel & transport enquiry</h2><input name="destination" required placeholder="Destination" /><input type="date" name="travelDate" required /><p className="service-label">What do you need?</p><div className="service-options"><button type="button" className={service === "Hotel stay" ? "selected" : ""} onClick={() => setService("Hotel stay")}>Hotel stay</button><button type="button" className={service === "Transport" ? "selected" : ""} onClick={() => setService("Transport")}>Transport</button><button type="button" className={service === "Hotel and transport" ? "selected" : ""} onClick={() => setService("Hotel and transport")}>Both</button></div><button>Send enquiry for {service.toLowerCase()}</button></form></div>{notice && <p className="planner-notice">{notice}</p>}<Link to="/login" className="details-btn">User sign in / create account →</Link></main>;
}
